# Register environments from libraries
import minatar
import ple
# import gym_minatar
# import gym_pygame

import json
import logging
import matplotlib.pyplot as plt
import matplotlib.ticker as tck
import numpy as np
import os
import pandas as pd
import random
import rltrain.utils.builders as mk
import seaborn as sns
import sys
import time
import torch as T

from pathlib import Path
from rltrain.env import MDP
from tap import Tap

DT_LOG = "%X %x (%z)"
DT_SAVE = "%Y-%m-%d_%H-%M-%S (%z)"
LOG_FORMAT = "%(asctime)s [%(levelname)s] %(message)s"

class Parser(Tap):
    
    agents: list[Path]
    env: Path
    dump: Path
    
    num_steps: int = 100000
    checkpoint_steps: int = 2500
    reward_run_rate: float = 0.1
    img: bool = False
    gpu: bool = False
    
    workers: int = 12
    log_freq: int = 1
    log_level = logging.INFO
    save_all: bool = False
    seed: int = int(time.time())

# Avoids error about duplicate versions of Intel's Math Kernel Library (MKL)
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"
# Prevent pygame from opening real windows
os.environ["SDL_VIDEODRIVER"] = "dummy"
# Ensures reproducibility on GPU
T.backends.cudnn.deterministic = True
# Styles graphs generated by matplotlib
sns.set_style("darkgrid")
sns.set_context("paper")

args = Parser(fromfile_prefix_chars='@').parse_args()
level = args.log_level if isinstance(args.log_level, int) else getattr(logging, args.log_level)
logging.basicConfig(stream=sys.stdout, level=level, format=LOG_FORMAT)

log = logging.getLogger("Train")
log.info("-----------------------")
log.info("******* RLTrain *******")
log.info("-----------------------")

log.info("obtaining available device information...")
device = T.device("cuda") if args.gpu and T.cuda.is_available() else T.device("cpu")
log.info(f"{device=}")

# Enables PyTorch multithreading
if args.workers != 1:
    T.set_num_threads(args.workers)
    T.set_num_interop_threads(args.workers)

def train(args: Parser):
    for agent_path in args.agents:
        log.info("seeding global RNGs...")
        random.seed(args.seed)
        np.random.seed(args.seed)
        T.manual_seed(args.seed)
        log.info(f"seed={args.seed}")
        
        log.info("parsing JSON from configuration files...")
        agent_str = agent_path.read_text()
        env_str = args.env.read_text()
        agent_cfg = json.loads(agent_str)
        env_cfg = json.loads(env_str)
        
        log.info("instantiating objects from parsed JSON...")
        start_time = time.time()
        agent = mk.agent(device=device, **agent_cfg)
        env = MDP(mk.env(**env_cfg), args.reward_run_rate, args.log_freq, args.img)
        
        log.info(f"agent={agent.name}")
        log.info(f"model={agent.model}")
        log.info(f"env={env_cfg['id']}")
        
        checkpoint_path = args.dump/agent.name
        timestamp_path = checkpoint_path/time.strftime(DT_SAVE, time.gmtime(start_time))
        models_path = timestamp_path/"models"
        cfg_path = timestamp_path/"config"
        csv_path = timestamp_path/"metrics.csv"
        episode_plot_path = timestamp_path/"per_episode.svg"
        sample_plot_path = timestamp_path/"per_sample.svg"
        
        log.info(f"saving training configuration to '{cfg_path}'...")
        cfg_path.mkdir(parents=True, exist_ok=True)
        models_path.mkdir(parents=True, exist_ok=True)
        (cfg_path/"seed.txt").write_text(f"{args.seed}")
        (cfg_path/"agent.json").write_text(agent_str)
        (cfg_path/"env.json").write_text(env_str)
        
        log.info(f"starting at {time.strftime(DT_LOG, time.gmtime(start_time))}...")
        agent.setup()
        env.setup(args.seed)
        last_checkpoint = 0
        
        while env.total_steps < args.num_steps:
            agent.step(env)
            
            # Save model (optionally) + plot graphs of returns per episode / timestep
            if (env.episode_steps != last_checkpoint and 
                    (env.total_steps % args.checkpoint_steps == 0 
                        or env.total_steps >= args.num_steps)
                ):
                
                current_time = time.time()
                last_checkpoint = env.episode_steps
                
                log.info(f"saving at: {time.strftime(DT_LOG, time.gmtime(current_time))}...")
                if args.save_all:
                    model_path = models_path/f"model_{last_checkpoint}.pt"
                    T.save(agent.model.state_dict(), model_path)
                
                pd.DataFrame({
                    "Episode": np.arange(1, env.episode_count + 1),
                    "Length": np.asarray(env.length_history),
                    "Return": np.asarray(env.return_history),
                    "Running Return": np.asarray(env.run_history)
                }).set_index("Episode").to_csv(csv_path)
                
                log.debug("plotting episode graph...")
                fig = plt.figure(dpi=600, clear=True)
                ax = plt.gca()
                x = np.arange(1, env.episode_count + 1)
                y1 = np.asarray(env.return_history)
                y2 = np.asarray(env.run_history)
                
                plt.title(f"Return over Episodes ({agent.name})")
                plt.xlabel("Episode")
                plt.ylabel("Return")
                plt.xlim(1, env.episode_count + 1)
                ax.xaxis.set_major_locator(tck.MaxNLocator(integer=True))
                
                if env.target_reward is not None:
                    ax.set_ylim(min(env.target_reward, y1.min(), y2.min()),
                                max(env.target_reward, y1.max(), y2.max()))
                    plt.axhline(env.target_reward, linestyle="dashed", color="black", label="Target")
                
                sns.lineplot(x=x, y=y1, color="orange", alpha=0.67, label="Return")
                sns.lineplot(x=x, y=y2, color="blue", label=r"EMA ($\beta = "f"{env.run_beta}"r"$)")
                plt.legend()
                plt.plot()
                plt.savefig(episode_plot_path, format="svg")
                plt.close(fig)
                
                log.debug("plotting per-sample graph...")
                fig = plt.figure(dpi=600, clear=True)
                ax = plt.gca()
                x = np.asarray(env.length_history).cumsum()
                y1 = np.asarray(env.return_history)
                y2 = np.asarray(env.run_history)
                
                plt.title(f"Return over Timesteps ({agent.name})")
                plt.xlabel("Timestep")
                plt.ylabel("Return")
                plt.xlim(0, max(args.num_steps, env.episode_steps))
                ax.xaxis.set_major_locator(tck.MaxNLocator(integer=True))
                
                if env.target_reward is not None:
                    ax.set_ylim(min(env.target_reward, y1.min(), y2.min()),
                                max(env.target_reward, y1.max(), y2.max()))
                    plt.axhline(env.target_reward, linestyle="dashed", color="black", label="Target")
                
                sns.lineplot(x=x, y=y1, color="orange", alpha=0.67, label="Return")
                sns.lineplot(x=x, y=y2, color="blue", label=r"EMA ($\beta = "f"{env.run_beta}"r"$)")
                plt.legend()
                plt.plot()
                plt.savefig(sample_plot_path, format="svg")
                plt.close(fig)
        
        log.info(f"finished training {agent.name} on {env_cfg['id']}!")
        T.save(agent.model.state_dict(), models_path/"model_FINAL.pt")

if __name__ == "__main__":
    train(args)
    log.info("all agents' training completed!")
